apiVersion: v1
kind: PersistentVolume
metadata:
  name: blogpost-pv-data
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/blogpost/data
  persistentVolumeReclaimPolicy: Retain

---
#media
apiVersion: v1
kind: PersistentVolume
metadata:
  name: blogpost-pv-media
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/blogpost/media
  persistentVolumeReclaimPolicy: Retain


