apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
stringData:
  DEBUG: "True"
  SECRET_KEY: "django-insecure-!b^9h+-kgizj4ml2%dr%5$6pqlx0=*^*-i8a3(bifk6t45*8@-"
  ALLOWED_HOSTS: "127.0.0.1,localhost"
  DATABASE_URL: "sqlite:///db.sqlite3"



